# generate-sitemap.ps1
# Sprint 8 — generates sitemap.xml from ROUTE_MAP.md Required Launch routes (Section 13).
# Governed by: ROUTE_MAP.md, IMPLEMENTATION_PLAN.md Sprint 8, scripts/README.md.
#
# A route enters sitemap.xml only if its index.html exists.
# Excludes preview/, data/, assets/, scripts/, governance/decisions/, and non-launch routes.

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$baseUrl = 'https://aidatanaly.com'

function Get-LaunchRoutes {
  param([string]$RouteMapPath)
  $lines = Get-Content -Encoding UTF8 -Path $RouteMapPath
  return @($lines | ForEach-Object { $_.Trim() } |
    Where-Object { $_ -match '^/[a-z0-9\-/\.]*$' } | Sort-Object -Unique)
}

function Get-PagePath {
  param([string]$Route, [string]$Root)
  if ($Route -eq '/') { return Join-Path $Root 'index.html' }
  $rel = ($Route.Trim('/') -replace '/', '\') + '\index.html'
  return Join-Path $Root $rel
}

Write-Host "=== AIDAtanaly Sitemap Generation ==="

$routeMapPath = Join-Path $root 'ROUTE_MAP.md'
$launchRoutes = Get-LaunchRoutes $routeMapPath
$pageRoutes = @($launchRoutes | Where-Object { $_ -notmatch '\.json$' })

if ($pageRoutes.Count -ne 41) {
  Write-Error "Expected 41 Required Launch page routes in ROUTE_MAP.md, found $($pageRoutes.Count)"
}

$implemented = @()
$missing = @()
foreach ($route in ($pageRoutes | Sort-Object)) {
  $pagePath = Get-PagePath $route $root
  if (Test-Path $pagePath) { $implemented += $route }
  else { $missing += $route }
}

Write-Host "  INFO  Implemented routes: $($implemented.Count)/41"

if ($missing.Count -gt 0) {
  Write-Error "Missing index.html for Required Launch route(s): $($missing -join ', ')"
}

$urlEntries = ($implemented | Sort-Object {
  if ($_ -eq '/') { '' } else { $_ }
} | ForEach-Object {
  $loc = if ($_ -eq '/') { "$baseUrl/" } else { "$baseUrl$_" }
  "  <url>`r`n    <loc>$loc</loc>`r`n  </url>"
}) -join "`r`n"

$xml = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.ps1 - do not edit by hand -->
<!-- Source: ROUTE_MAP.md Section 13 (41 Required Launch routes) -->
<!-- Pre-launch: robots.txt remains Disallow: / until PUBLIC_RELEASE_PLAN.md -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
$urlEntries
</urlset>
"@

$outPath = Join-Path $root 'sitemap.xml'
[System.IO.File]::WriteAllText($outPath, $xml.TrimEnd() + "`r`n", [System.Text.UTF8Encoding]::new($false))
Write-Host "  OK    Wrote $outPath ($($implemented.Count) URLs)"
Write-Host "=== Done ==="
